networks:
  jenkins:
volumes:
  jenkins-data:
  jenkins-docker-certs:
services:
  jenkins-docker:
    image: docker:dind
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    privileged: true  # needed for DinD
  jenkins-controller:
    image: controller
    build: ./controller
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000" # Might be deprecated
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    links:
      - jenkins-docker:docker # alias


